# Generated by Django 2.2.16 on 2025-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_businesshours_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Prix en Francs CFA', max_digits=10),
        ),
    ]
